language: generic
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_1d8c94bea0f3_key -iv $encrypted_1d8c94bea0f3_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
script:
- "./bootstrap.sh"
deploy:
- provider: script
  script: bash deploy-ssh.sh
  on:
    branch: master
